xlab <- "Number of identified viral targets in HuSCI"
ylab <- "Fraction of\n random networks"
pdf("~/Documents/INET-work/virus_network/Y2H_screening/20201104_final/figures/random_GWAS_3phenotype.pdf", width = 3, height = 3)
par(mgp = c(2, 0.7, 0), ps = 8)
# 16 GWAS hits
dens <- hist(random_gwas_all_final, breaks = 25, plot = FALSE)
plot(dens, xlim = c(0, 25), col = rgb(0.75, 0.75, 0.75, 1/2), freq = FALSE, border = NA, las = 1, xlab = xlab, ylab = ylab, xaxt = "n", main = "Identified HuSCI viral targets\nin 10000 randomized network")
mtext(side = 3, line = 0.1, cex = 1, paste0("interactors of ", length(gwas_all), " GWAS hits"))
axis(side = 1, at = seq(1, 25, 4) - 0.5, labels = seq(0, 24, 4), line = 0.3)
arrows(gwas_1stN_inHuSCI + 0.5, 0.02, gwas_1stN_inHuSCI + 0.5, 0, col = "#922687", lwd = 2, length = 0.1)
text(gwas_1stN_inHuSCI - 1, 0.03, paste0("p = ", table(random_gwas_all_final >= gwas_1stN_inHuSCI)["TRUE"]/10000), cex = 0.7, pos = 4)
# GWAS hits with critical infection phenotype
dens <- hist(random_gwas_ctcl_final, breaks = 10, plot = FALSE)
plot(dens, xlim = c(0, 15), col = rgb(0.75, 0.75, 0.75, 1/2), freq = FALSE, border = NA, las = 1, xlab = "", ylab = "", xaxt = "n", main = "Identified HuSCI viral targets\nin 10000 randomized network")
mtext(side = 3, line = 0.1, cex = 1, paste0("interactors of ", length(ctcl), " GWAS hits associated with \ncritical illness"))
mtext(side = 1, line = 2, cex = 1, xlab)
mtext(side = 2, line = 2, cex = 1, ylab)
axis(side = 1, at = seq(1, 15, 3) - 0.5, labels = seq(0, 14, 3), line = 0.3)
arrows(gwas_ctcl_inHuSCI + 0.5, 0.03, gwas_ctcl_inHuSCI + 0.5, 0, col = "#922687", lwd = 2, length = 0.1)
text(gwas_ctcl_inHuSCI - 0.5, 0.04, paste0("p = ", table(random_gwas_ctcl_final >= gwas_ctcl_inHuSCI)["TRUE"]/10000), cex = 0.7, pos = 4)
# GWAS hits with hospitalization phenotype
dens <- hist(random_gwas_hosp_final, breaks = 20, plot = FALSE)
plot(dens, xlim = c(0, 25), col = rgb(0.75, 0.75, 0.75, 1/2), freq = FALSE, border = NA, las = 1, xlab = "", ylab = "", xaxt = "n", main = "Identified HuSCI viral targets\nin 10000 randomized network")
mtext(side = 3, line = 0.1, cex = 1, paste0("interactors of ", length(hosp), " GWAS hits associated with \nhospitalization"))
mtext(side = 1, line = 2, cex = 1, xlab)
mtext(side = 2, line = 2, cex = 1, ylab)
axis(side = 1, at = seq(1, 25, 4) - 0.5, labels = seq(0, 24, 4), line = 0.3)
arrows(gwas_hosp_inHuSCI + 0.5, 0.02, gwas_hosp_inHuSCI + 0.5, 0, col = "#922687", lwd = 2, length = 0.1)
text(gwas_hosp_inHuSCI - 1, 0.03, paste0("p = ", table(random_gwas_hosp_final >= gwas_hosp_inHuSCI)["TRUE"]/10000), cex = 0.7, pos = 4)
# GWAS hits with infection phenotype
dens <- hist(random_gwas_infct_final, breaks = 5, plot = FALSE)
plot(dens, xlim = c(0, 10), col = rgb(0.75, 0.75, 0.75, 1/2), freq = FALSE, border = NA, las = 1, xlab = "", ylab = "", xaxt = "n", main = "Identified HuSCI viral targets\nin 10000 randomized network")
mtext(side = 3, line = 0.1, cex = 1, paste0("interactors of ", length(infct), " GWAS hits associated with\n infection"))
mtext(side = 1, line = 2, cex = 1, xlab)
mtext(side = 2, line = 2, cex = 1, ylab)
axis(side = 1, at = seq(1, 10, 2) - 0.5, labels = seq(0, 9, 2), line = 0.3)
arrows(gwas_infct_inHuSCI + 0.5, 0.07, gwas_infct_inHuSCI + 0.5, 10/10000, col = "#922687", lwd = 2, length = 0.1)
text(gwas_infct_inHuSCI - 1, 0.1, paste0("p = ", table(random_gwas_infct_final >= gwas_infct_inHuSCI)["TRUE"]/10000), cex = 0.7, pos = 4)
dev.off()
